if(!window.criteo_q||window.criteo_q instanceof Array){var oldQueue=window.criteo_q||[];window.criteo_q=function(){function g(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var f=b[c],d=f.substr(0,f.indexOf("=")).replace(/^\s+|\s+$/g,""),f=f.substr(f.indexOf("=")+1);if(d===a)return(decodeURIComponent||unescape)(f)}return null}function v(a,b){if(a&&1<a.length){"?"===a[0]&&(a="&"+a.substr(1));var c="&"+b+"=",f=a.indexOf(c);if(-1!==f){var d=a.indexOf("&",f+c.length);return a.slice(f+c.length,
0>d?void 0:d)}}}var e={bodyReady:!1,domReady:!1,queue:[],actions:[],disingScheduled:[],accounts:[],acid:null,axid:null,pxsig:null,idcpy:null,optout:!1,ccp:null,cop:null},d={tagVersion:"4.4.5",handlerUrlPrefix:("https:"===document.location.protocol?"https://sslwidget.":"http://widget.")+"criteo.com/event",handlerResponseType:"single",responseType:"js",handlerParams:{v:"4.4.5"},extraData:[],customerInfo:[],manualDising:!1,manualFlush:!1,disOnce:!1,partialDis:!1,guidCookieName:"cto_idcpy",guidCookieRetentionTimeHours:9490,
optoutCookieName:"cto_optout",optoutCookieRetentionTimeHours:43800,gumSyncFrameEndPoint:"https://gum.criteo.com/syncframe",gumSyncFrameId:"criteo-syncframe",forceSyncFrame:!1,eventMap:{applaunched:"al",viewitem:"vp",viewhome:"vh",viewlist:"vl",viewbasket:"vb",viewsearch:"vs",tracktransaction:"vc",calldising:"dis",setdata:"exd",setemail:"ce"},propMap:{event:"e",account:"a",currency:"c",product:"p",item:"p","item.id":"i","item.price":"pr","item.quantity":"q","product.id":"i","product.price":"pr","product.quantity":"q",
data:"d",keywords:"kw",checkin_date:"din",checkout_date:"dout",deduplication:"dd",attribution:"at","attribution.channel":"ac","attribution.value":"v",user_segment:"si",new_customer:"nc",customer_id:"ci",email:"m",hash_method:"h",transaction_value:"tv",responseType:"rt"},setters:{seturl:{cfg:"handlerUrlPrefix",evt:"url"},setaccount:{cfg:"account",evt:"account"},setcalltype:{cfg:"handlerResponseType",evt:"type"},setresponsetype:{cfg:"responseType",evt:"type"},oninitialized:{cfg:"onInitialized",evt:"callback"},
ondomready:{cfg:"onDOMReady",evt:"callback"},beforeappend:{cfg:"beforeAppend",evt:"callback"},aftereval:{cfg:"afterEval",evt:"callback"},onflush:{cfg:"onFlush",evt:"callback"}},flags:{disonce:"disOnce",manualdising:"manualDising",manualflush:"manualFlush",nopartialflush:"noPartialFlush",disonpartialflush:"partialDis"}},w=function(a,b,c){var f=new Date;f.setTime(f.getTime()+36E5*c);c="expires="+f.toUTCString();for(var f=document.location.hostname.split("."),d=0;d<f.length;++d){var e=f.slice(f.length-
d-1,f.length).join("."),e="domain=."+e;document.cookie=a+"="+(encodeURIComponent||escape)(b)+";"+c+";"+e+";path=/";if((e=g(a))&&e===b)break}},D=function(){var a=document.createElement("iframe");a.src=d.gumSyncFrameEndPoint;a.id=d.gumSyncFrameId;a.width=0;a.height=0;a.frameBorder=0;a.setAttribute("style","border-width:0px; margin:0px; display:none");return a},r=function(a,b,c){w(a,b,c);if(window.localStorage)try{window.localStorage.setItem(a,b)}catch(f){}},E=function(){if(navigator.userAgent.match(/^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[^ ]+ \(KHTML, like Gecko\) Version\/([^ ]+)( Mobile\/[^ ]+)? Safari\/[^ ]+$/i)&&
window.addEventListener||d.forceSyncFrame){var a=D(),b=function(b){b=b.data;b.isCriteoMessage&&(b.optout?(e.optout=!0,r(d.optoutCookieName,"1",d.optoutCookieRetentionTimeHours),b=d.guidCookieName,w(b,"",0),window.localStorage&&window.localStorage.removeItem(b)):b.uid?(b=b.uid,e.idcpy=b,r(d.guidCookieName,b,d.guidCookieRetentionTimeHours)):a.contentWindow.postMessage({uid:e.idcpy},"*"))};window.addEventListener&&(window.addEventListener("message",b,!1),e.queue.push({event:"appendtag",element:a}))}},
s=function(a){if(a&&a.referrer){var b=a.createElement("a");b.href=a.referrer;return b}return null};(function(a){var b;window.localStorage&&(b=window.localStorage.getItem(d.guidCookieName));var c=e.idcpy||b;if(e.idcpy&&!b||!e.idcpy&&b)e.idcpy=c,r(d.guidCookieName,c,d.guidCookieRetentionTimeHours);a.idcpy=c;a.optout=Boolean(g(d.optoutCookieName))})(e);(function(a){var b=g("criteo_acid"),c=g("cto_axid"),f=g("cto_pxsig"),d=g("cto_optout");null===b&&null===c&&null===d&&null===f?(b=new Date,b.setTime(b.getTime()+
1E4),b="expires="+b.toUTCString(),document.cookie=["criteo_write_test=ChUIBBINbXlHb29nbGVSdGJJZBgBIAE","path=/",b].join("; "),b=g("criteo_write_test"),a.canWriteCookie=null!==b,document.cookie="criteo_write_test=; path=/; expires=Thu, 01 Jan 1970 00:00:00 UTC"):(a.acid=b,a.axid=null!==d?"optout":c,a.pxsig=f,a.canWriteCookie=!0)})(e);(function(a,b){var c,d;try{d=a.top.location.search}catch(e){var h=a;try{for(;h.parent.document!==h.document;)if(h.parent.document)h=h.parent;else break}catch(l){}if(h&&
(h=s(h.document)))d=h.search}d&&(c=v(d,"cto_pld"));if(!c)try{var g=s(a.top.document);g&&g.search&&(c=v(g.search,"cto_pld"))}catch(m){}c&&(b.cop=c)})(window,e);(function(a){var b=g("criteo_cookie_perm");null!==b&&(a.ccp=b)})(e);var x=function(){for(var a=0;a<arguments.length;++a)e.queue.push(arguments[a]);t()},t=function(){for(var a=[],b=e.queue,c=0;c<b.length;++c){var f=b[c];if(f instanceof Array)b.splice.apply(b,[c+1,0].concat(f));else if(f instanceof Function)b.splice(c+1,0,f());else if(f&&"[object Object]"===
f.toString())switch(n(f,c,b,a)){case 0:a.push(f);break;case -1:a=a.concat(b.slice(c)),c=b.length}}d.afterEval instanceof Function&&(a=d.afterEval(b,a,e,d));e.queue=a||[];!d.manualFlush&&(!d.noPartialFlush||0===e.queue.length)&&y(0!==e.queue.length)},n=function(a,b,c,f){if(!e.domReady&&a.requiresDOM&&"no"!==a.requiresDOM)return"blocking"===a.requiresDOM?-1:0;delete a.requiresDOM;if(!a.event)return l(a),1;a.account&&u(a.account,e.accounts);a.event=a.event.toLowerCase();switch(a.event){case "setdata":return a=
l(a),d.extraData.push(a),z(e.actions,l(a)),1;case "setparameter":for(var k in a)"event"!==k.toLowerCase()&&a.hasOwnProperty(k)&&(d.handlerParams[k]=a[k]);return 1;case "calldising":a.hasOwnProperty("account")||(a.account=e.accounts);b=d.handlerResponseType;a.hasOwnProperty("type")&&(b=a.type,delete a.type);u(a.account,e.disingScheduled);"sequential"===b&&(a.dc=!0);break;case "setcustomerid":return a.event="setdata",a.customer_id=a.id,delete a.id,n(a);case "setemail":case "sethashedemail":case "ceh":a.event=
"setemail";if(a.hasOwnProperty("email")){a.email instanceof Array||(a.email=[a.email]);b=a.email;c=[];for(f=0;f<b.length;f++)void 0!==b[f]&&null!==b[f]&&c.push(String(b[f]));a.email=c}b=l(a);d.customerInfo.push(b);A(e.actions,l(a));return 1;case "setsitetype":b="d";if("mobile"===a.type||"m"===a.type)b="m";if("tablet"===a.type||"t"===a.type)b="t";a.event="setdata";delete a.type;a.site_type=b;return n(a);case "appendtag":e.bodyReady&&!d.container&&((b=document.body)?(c=document.createElement("div"),
c.setAttribute("id","criteo-tags-div"),c.style.display="none",b.appendChild(c),b=c):b=void 0,d.container=b);a.url&&(a.isImgUrl?(b=document.createElement("img"),b.setAttribute("style","display:none;"),b.setAttribute("width","1"),b.setAttribute("height","1")):(b=document.createElement("script"),b.setAttribute("async","true"),b.setAttribute("type","text/javascript")),b.setAttribute("src",a.url),a.element=b);d.beforeAppend instanceof Function&&(a.element=d.beforeAppend(a.element,e,d));l(a);if(a.element&&
(a.element.tagName||a.isImgUrl))if(!d.container&&("script"===a.element.tagName.toLowerCase()||a.isImgUrl))b=document.getElementsByTagName("script")[0],a.element.setAttribute("data-owner","criteo-tag"),b.parentNode.insertBefore(a.element,b);else if(d.container)d.container.appendChild(a.element);else return 0;return 1;case "gettagstate":return a.callback instanceof Function?a.callback(e,d):1;case "flush":case "flushevents":return y(b!==c.length-1||0!==f.length),1}if(b=d.setters[a.event])return d[b.cfg]=
a[b.evt],1;if(b=d.flags[a.event])return d[b]=!0,1;e.actions.push(l(a));return 1},y=function(a){d.onFlush instanceof Function&&(e.actions=d.onFlush(e.actions,e,d));if(0!==e.actions.length){for(var b=0;b<d.extraData.length;++b)z(e.actions,d.extraData[b]);for(b=0;b<d.customerInfo.length;++b)A(e.actions,d.customerInfo[b]);if(!d.manualDising&&(!a||d.partialDis)){a=[];for(b=0;b<e.accounts.length;++b)q(e.disingScheduled,e.accounts[b])||a.push(e.accounts[b]);0<a.length&&n({event:"callDising",account:a})}a=
e.actions;b=[];1===e.accounts.length&&(d.account=e.accounts[0]);d.account&&b.push("a="+m(d.account,[]));"js"!==d.responseType&&b.push("rt="+m(d.responseType,[]));if(d.handlerParams){var c=decodeURIComponent(m(d.handlerParams,[]));c&&b.push(c)}for(c=0;c<a.length;++c)a[c].account&&p(d.account,a[c].account)&&delete a[c].account,b.push("p"+c+"="+m(a[c],[]));null!==e.acid&&b.push("acid="+e.acid);null!==e.axid&&b.push("axid="+e.axid);null!==e.pxsig&&b.push("pxsig="+e.pxsig);e.canWriteCookie&&b.push("adce=1");
null!==e.ccp&&b.push("ccp="+e.ccp);null!==e.cop&&b.push("cop="+e.cop);e.idcpy&&(b.push("idcpy="+e.idcpy),b.push("iddom="+document.location.hostname));e.optout&&b.push("optout=1");a=b.join("&");a={event:"appendTag",url:d.handlerUrlPrefix+"?"+a,isImgUrl:"gif"===d.responseType};e.actions=[];n(a);d.disOnce||(e.disingScheduled=[])}},z=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.event===b.event&&p(b.account,d.account)){for(var e in b)b.hasOwnProperty(e)&&"account"!==e&&(d[e]=b[e]);return}}a.push(b)},
A=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.event===b.event&&p(b.account,d.account)&&("hash_method"in b?b.hash_method:"")===("hash_method"in d?d.hash_method:"")){if(b.hasOwnProperty("email")){for(var c=d,d=d.email,e=b.email,h=[],g=0;g<e.length;++g)q(d,e[g])||h.push(e[g]);d=d.concat(h);c.email=d}return}}a.push(b)},l=function(a){var b=a;if(a instanceof Function)return b=a(),b instanceof Function?b:l(b);if(a instanceof Array)for(var b=[],c=0;c<a.length;++c)b[c]=l(a[c]);else if(a&&"[object Object]"===
a.toString())for(c in b={},a)a.hasOwnProperty(c)&&(b[c]=l(a[c]));return b},G=function(a,b){var c=b.join(".");return d.propMap[c]?d.propMap[c]:a},p=function(a,b){if(!(a instanceof Array))return p([a],b);if(!(b instanceof Array))return p(a,[b]);if(a.length!==b.length)return!1;for(var c=0;c<a.length;++c)if(!q(b,a[c]))return!1;return!0},m=function(a,b){var c="";if(a instanceof Function)c=m(a(),b);else if(a instanceof Array){for(var e=[],k=0;k<a.length;++k)e[k]=m(a[k],b);c+="["+e.join(",")+"]"}else if(a&&
"[object Object]"===a.toString()){e=[];for(k in a)if(a.hasOwnProperty(k)){var h=b.concat([k]);e.push(G(k,h)+"="+m(a[k],h))}c+=e.join("&")}else c=1===b.length&&"event"===b[0]?c+(d.eventMap[a.toLowerCase()]?d.eventMap[a.toLowerCase()]:a):c+a;return encodeURIComponent(c)},u=function(a,b){if(a instanceof Array)for(var c=0;c<a.length;++c)u(a[c],b);else q(b,a)||b.push(a)},q=function(a,b){for(var c=0;c<a.length;++c)if(a[c]===b)return!0;return!1},H=function(a){if(a){var b=a.createElement("script");b.setAttribute("type",
"text/javascript");b.setAttribute("src",a.location.protocol+"//static.criteo.net/js/ld/ld-tag-debug.4.4.5.js");a=a.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}};(function(a){(function c(){document.body?setTimeout(a,0):setTimeout(c,10)})()})(function(){e.bodyReady=d.onInitialized instanceof Function?d.onInitialized(e,d):!0;E();t()});(function(a,b){if("complete"===a.readyState)b();else if(a.addEventListener)a.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",
b,!1);else{a.attachEvent("onreadystatechange",b);window.attachEvent("onload",b);var c=!1;try{c=null===window.frameElement&&document.documentElement}catch(d){}if(c&&c.doScroll)(function F(){if(c){try{c.doScroll("left")}catch(a){return setTimeout(F,50)}b()}})();else{var e=!1,h=a.onload,g=a.onreadystatechange;a.onload=a.onreadystatechange=function(){g instanceof Function&&g();if(!e&&(!a.readyState||"loaded"===a.readyState||"complete"===a.readyState))h instanceof Function&&h(),e=!0,b()}}}})(document,
function(){e.domReady=d.onDOMReady instanceof Function?d.onDOMReady(e,d):!0;t()});(function(a){try{var b=s(a);b&&b.hostname!==a.location.hostname&&d.extraData.push({event:"setData",ref:b.protocol+"//"+b.hostname})}catch(c){}})(document);(function(a,b){if(a&&b){var c=/^\#(enable|disable)-criteo-tag-debug-mode(\=(\d+))?$/.exec(b);if(c&&4==c.length){var d="enable"==c[1],e=c[3],c="criteoTagDebugMode=";d&&(e&&!isNaN(e))&&(c+=parseInt(e,10));d=d?(new Date).getTime()+864E5:0;d="expires="+(new Date(d)).toUTCString();
document.cookie=[c,"path=/",d].join("; ");window.location.href=window.location.href.substr(0,window.location.href.indexOf("#"))}}})(document,window.location.hash);var B;B=document?"function"!=typeof Array.prototype.indexOf?!1:-1!==document.cookie.indexOf("criteoTagDebugMode="):!1;if(B){var C={originalPush:x,stagedPushes:[],stagedErrors:[],push:function(){0<arguments.length&&this.stagedPushes.push(arguments)},pushError:function(a){this.stagedErrors.push(a)}};window.onerror=function(a){return function(b,
c,d,e){C.pushError({message:b,url:c,lineNumber:d,column:e});return a&&"function"===typeof a?a.apply(this,arguments):!1}}(window.onerror);H(document);return C}return{push:x}}();window.criteo_q.push.apply(window.criteo_q,oldQueue)};
